'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Mono Runtime Version: 4.0.30319.17020
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Explicit On
Option Strict On

Imports System
Imports System.Web
Imports System.Web.UI


Partial Public Class [Default]
	
	Protected button1 As System.Web.UI.WebControls.Button
End Class

