'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Mono Runtime Version: 4.0.30319.17020
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Explicit On
Option Strict On



Partial Public Class Master
	
	Protected Main As System.Web.UI.WebControls.ContentPlaceHolder
End Class
